### ISSUE TITLE
use of np.isclose to compare number close to 0

### ISSUE THREAD

**Issue by nicolas-UKLSL** [pbrod/nvector#12]
According to numpy documentation (v1.19), isclose should not be used with default atol value for comparing numbers close to 0. See https://numpy.org/doc/stable/reference/generated/numpy.isclose.html

However, this is what is done in  function on_great_circle in _core.py (and maybe other areas).

**Comment by pbrod** [comment]
Well it depends on the scale of the application and the desired accurracy. 
In nvector the scale is on the order of the radius of the earth which is about 6.37*10^6 meters. 
In the on_great_circle  function  np.isclose checks if  absolute(distance - 0) <= (atol + rtol * absolute(0)) = atol = 1e-8
In other words if the position differ with 10^-8 meters it is on the great circle path.
I would say that is reasonable.  Actually it is calculated to machine precision because atol is approximately equal to the earth radius times 10^-14.  
For my applications I would even accept it to be on the great circle if the position differ with less than 1 meter, which corresponds to a single precison calculation.

**Comment by nicolas-UKLSL** [comment]
You are right, though because 0 is the second argument, rtol is not used. I would think it best to change from `np.isclose(distance, 0)` to `np.isclose(0, distance)`

**Comment by pbrod** [comment]
Hmmm... I think I will remove the rtol parameter since it is useless in this situation, but I am wondering if the default atol value is too strict. For practical application of gps data the error ranges from 0.01 meter to 15 meters according to
https://gis.stackexchange.com/questions/43617/what-is-the-maximum-theoretical-accuracy-of-gps.

**Comment by pbrod** [comment]
The documentation of np.isclose states that the default value of atol=1e-8 is  appropriate for expected values of order unity and I think that is the major use case for this library.

**Comment by nicolas-UKLSL** [comment]
Yes, I think this is fair
